// Generated by CoffeeScript 1.6.3
(function() {
  var i, roomdata, _i;

  roomdata = [];

  for (i = _i = 0; _i <= 4; i = ++_i) {
    roomdata[i] = {
      id: i,
      name: "room" + i
    };
  }

  Template.roomList.helpers({
    rooms: roomdata
  });

}).call(this);

/*
//@ sourceMappingURL=roomList.map
*/
