// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  if (Meteor.isClient) {
    Meteor.subscribe('messages');
  } else {
    Meteor.publish('messages', function() {
      return _this.Messages.find();
    });
  }

  this.Messages = new Meteor.Collection('messages');

  if (Meteor.isServer) {
    Meteor.methods({
      send: function(message) {
        var name, user;
        user = Meteor.user();
        if (!user) {
          throw new Meteor.Error(401, "You need to login to chat!");
        }
        if (!message.text) {
          throw new Meteor.Error(422, "Cannot send blank messages.");
        }
        if (user.username || user.emails) {
          name = user.username || user.emails[0].address;
        } else {
          name = user.profile.name;
        }
        message.name = name;
        return _this.Messages.insert(message);
      }
    });
  }

}).call(this);

/*
//@ sourceMappingURL=collections.map
*/
